---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  labels:
    name: hello-world
spec:
  replicas: 10
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: csanchez/hello-world:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080